// <auto-generated />
namespace AERHiPets.DAL.GestionUsuariosDAL.Migrations2
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class USR1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(USR1));
        
        string IMigrationMetadata.Id
        {
            get { return "201509022138297_USR1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
