// <auto-generated />
namespace AERHiPets.DAL.GestionVoluntariosDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class VOL5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VOL5));
        
        string IMigrationMetadata.Id
        {
            get { return "201510152044308_VOL5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
