// <auto-generated />
namespace AERHiPets.DAL.GestionAdopcionApadrinamiento.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ADOP26 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADOP26));
        
        string IMigrationMetadata.Id
        {
            get { return "201510222058594_ADOP26"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
