//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AERHiPets.DAL.NewDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adopcions
    {
        public int Id { get; set; }
        public Nullable<int> empleadoId { get; set; }
        public Nullable<int> voluntarioId { get; set; }
        public Nullable<int> animalId { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaCancelacion { get; set; }
        public Nullable<System.DateTime> fechaConfirmacion { get; set; }
        public Nullable<int> dias { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public Nullable<System.DateTime> fechaEntrega { get; set; }
        public bool esTemporal { get; set; }
        public Nullable<int> estadoAdopcionId { get; set; }
        public Nullable<int> tipoAdopcionId { get; set; }
        public Nullable<int> direccionId { get; set; }
        public string VoluntarioUsrId { get; set; }
        public string EmpleadoUsrId { get; set; }
        public string empleadoName { get; set; }
        public string voluntarioName { get; set; }
    
        public virtual Animals Animals { get; set; }
        public virtual Direccions Direccions { get; set; }
        public virtual EstadoAdopcions EstadoAdopcions { get; set; }
        public virtual Personas Personas { get; set; }
        public virtual Personas Personas1 { get; set; }
        public virtual TipoAdopcions TipoAdopcions { get; set; }
    }
}
