//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AERHiPets.DAL.NewDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtencionMedicas
    {
        public int Id { get; set; }
        public int animalId { get; set; }
        public int veterinariaId { get; set; }
        public Nullable<int> productoVeterinariaId { get; set; }
        public string tratamiento { get; set; }
        public string nombreVeterinario { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
    
        public virtual Animals Animals { get; set; }
        public virtual ProductoVeterinarias ProductoVeterinarias { get; set; }
        public virtual Veterinarias Veterinarias { get; set; }
    }
}
