//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AERHiPets.DAL.NewDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barrios
    {
        public Barrios()
        {
            this.Direccions = new HashSet<Direccions>();
        }
    
        public int Id { get; set; }
        public string nombre { get; set; }
        public string codigoPostal { get; set; }
        public int localidadId { get; set; }
    
        public virtual Localidads Localidads { get; set; }
        public virtual ICollection<Direccions> Direccions { get; set; }
    }
}
