//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AERHiPets.DAL.NewDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccions
    {
        public Direccions()
        {
            this.Adopcions = new HashSet<Adopcions>();
            this.Personas = new HashSet<Personas>();
        }
    
        public int Id { get; set; }
        public int barrioId { get; set; }
        public string calle { get; set; }
        public string piso { get; set; }
        public string Torre { get; set; }
        public string depto { get; set; }
    
        public virtual ICollection<Adopcions> Adopcions { get; set; }
        public virtual Barrios Barrios { get; set; }
        public virtual ICollection<Personas> Personas { get; set; }
    }
}
