//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AERHiPets.DAL.NewDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoAdopcions
    {
        public EstadoAdopcions()
        {
            this.Adopcions = new HashSet<Adopcions>();
        }
    
        public int Id { get; set; }
        public string descripcion { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Adopcions> Adopcions { get; set; }
    }
}
