//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AERHiPets.DAL.NewDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidentes
    {
        public Incidentes()
        {
            this.Files = new HashSet<Files>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> tamanioId { get; set; }
        public Nullable<int> razaId { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string telefono { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public string EstadoIncidente { get; set; }
        public Nullable<int> tipoIncidenteId { get; set; }
    
        public virtual ICollection<Files> Files { get; set; }
        public virtual Razas Razas { get; set; }
        public virtual Tamanios Tamanios { get; set; }
        public virtual TipoIncidentes TipoIncidentes { get; set; }
    }
}
