//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AERHiPets.DAL.NewDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localidads
    {
        public Localidads()
        {
            this.Barrios = new HashSet<Barrios>();
        }
    
        public int Id { get; set; }
        public string nombre { get; set; }
        public int provinciaId { get; set; }
    
        public virtual ICollection<Barrios> Barrios { get; set; }
        public virtual Provincias Provincias { get; set; }
    }
}
