//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AERHiPets.DAL.newnewdal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animals
    {
        public Animals()
        {
            this.Adopcions = new HashSet<Adopcions>();
            this.Apadrinamientoes = new HashSet<Apadrinamientoes>();
            this.AtencionMedicas = new HashSet<AtencionMedicas>();
            this.FilePaths = new HashSet<FilePaths>();
            this.Files = new HashSet<Files>();
        }
    
        public int Id { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaNac { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public int edad { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public string caracteristicas { get; set; }
        public Nullable<int> tamanioId { get; set; }
        public Nullable<int> razaId { get; set; }
        public bool enAdopcion { get; set; }
        public Nullable<int> especieID { get; set; }
        public string Discriminator { get; set; }
    
        public virtual ICollection<Adopcions> Adopcions { get; set; }
        public virtual Especies Especies { get; set; }
        public virtual Razas Razas { get; set; }
        public virtual Tamanios Tamanios { get; set; }
        public virtual ICollection<Apadrinamientoes> Apadrinamientoes { get; set; }
        public virtual ICollection<AtencionMedicas> AtencionMedicas { get; set; }
        public virtual ICollection<FilePaths> FilePaths { get; set; }
        public virtual ICollection<Files> Files { get; set; }
    }
}
