//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AERHiPets.DAL.newnewdal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidentes
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> tamanioId { get; set; }
        public Nullable<int> razaId { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string telefono { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public Nullable<int> tipoIncidenteId { get; set; }
        public Nullable<int> especieId { get; set; }
        public Nullable<int> estadoIncidenteId { get; set; }
        public string VoluntarioUsrId { get; set; }
        public string voluntarioName { get; set; }
        public Nullable<int> voluntarioId { get; set; }
        public string calle { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public Nullable<int> barrioId { get; set; }
    
        public virtual Barrios Barrios { get; set; }
        public virtual EstadoIncidentes EstadoIncidentes { get; set; }
        public virtual Personas Personas { get; set; }
        public virtual Razas Razas { get; set; }
        public virtual Razas Razas1 { get; set; }
        public virtual Tamanios Tamanios { get; set; }
        public virtual TipoIncidentes TipoIncidentes { get; set; }
    }
}
