//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AERHiPets.DAL.newnewdal
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeIncidencias
    {
        public Nullable<int> tipoIncidenteId { get; set; }
        public string Zona { get; set; }
        public string tipoIncidente { get; set; }
        public Nullable<int> especieId { get; set; }
        public string nombre { get; set; }
    }
}
