//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AERHiPets.DAL.newnewdal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paises
    {
        public Paises()
        {
            this.Provincias = new HashSet<Provincias>();
        }
    
        public int Id { get; set; }
        public string pais_nombre { get; set; }
    
        public virtual ICollection<Provincias> Provincias { get; set; }
    }
}
