//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AERHiPets.DAL.newnewdal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoVeterinarias
    {
        public ProductoVeterinarias()
        {
            this.AtencionMedicas = new HashSet<AtencionMedicas>();
        }
    
        public int Id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
    
        public virtual ICollection<AtencionMedicas> AtencionMedicas { get; set; }
    }
}
