// <auto-generated />
namespace AERHiPets.DAL.GestionAnimalesDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class GA1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GA1));
        
        string IMigrationMetadata.Id
        {
            get { return "201508180339025_GA1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
